-- Topheart church attendance system
-- Paste this file into the Supabase SQL Editor and run it once.
--
-- This version uses:
-- 1. A church hierarchy: 區長 > 大家長 > 小家長 > 小家人 > 新朋友(best)
-- 2. Custom LINE login via Edge Functions
-- 3. App-owned session tokens instead of Supabase Auth social login

begin;

create extension if not exists pgcrypto;

-- Reset old prototypes and previous MVP objects.
drop view if exists public.member_directory cascade;

drop function if exists public.set_updated_at() cascade;
drop function if exists public.mark_attendance(uuid, date, uuid, uuid, boolean, text) cascade;

drop table if exists public.app_sessions cascade;
drop table if exists public.line_pending_logins cascade;
drop table if exists public.line_auth_states cascade;
drop table if exists public.login_invites cascade;
drop table if exists public.attendance_records cascade;
drop table if exists public.attendance_weeks cascade;
drop table if exists public.members cascade;
drop table if exists public.small_groups cascade;
drop table if exists public.big_families cascade;
drop table if exists public.districts cascade;

drop table if exists public.group_members cascade;
drop table if exists public.app_users cascade;

drop type if exists public.attendance_status cascade;
drop type if exists public.attendance_event_type cascade;
drop type if exists public.member_gender cascade;
drop type if exists public.member_role cascade;
drop type if exists public.user_role cascade;

create type public.member_gender as enum (
  'brother',
  'sister'
);

create type public.member_role as enum (
  'district_leader',
  'big_family_leader',
  'small_group_leader',
  'member',
  'best'
);

create type public.attendance_event_type as enum (
  'sunday_service',
  'small_group_fellowship'
);

create type public.attendance_status as enum (
  'unknown',
  'present',
  'absent'
);

create table public.districts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint districts_name_not_blank check (btrim(name) <> '')
);

create table public.big_families (
  id bigint generated by default as identity primary key,
  district_id bigint not null references public.districts(id) on delete cascade,
  name text not null,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint big_families_name_not_blank check (btrim(name) <> ''),
  constraint big_families_name_per_district unique (district_id, name)
);

create table public.small_groups (
  id bigint generated by default as identity primary key,
  district_id bigint not null references public.districts(id) on delete cascade,
  big_family_id bigint references public.big_families(id) on delete cascade,
  name text not null,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint small_groups_name_not_blank check (btrim(name) <> '')
);

create table public.members (
  id bigint generated by default as identity primary key,
  full_name text not null,
  birthday date,
  gender public.member_gender,
  note text not null default '',
  role public.member_role not null,
  is_admin boolean not null default false,
  line_user_id text unique,
  district_id bigint references public.districts(id) on delete restrict,
  big_family_id bigint references public.big_families(id) on delete restrict,
  small_group_id bigint references public.small_groups(id) on delete restrict,
  is_active boolean not null default true,
  last_line_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint members_name_not_blank check (btrim(full_name) <> ''),
  constraint members_line_user_id_not_blank check (
    line_user_id is null or btrim(line_user_id) <> ''
  ),
  constraint members_scope_matches_role check (
    (
      role = 'district_leader'
      and district_id is not null
      and big_family_id is null
      and small_group_id is null
    )
    or (
      role = 'big_family_leader'
      and district_id is not null
      and big_family_id is not null
      and small_group_id is null
    )
    or (
      role in ('small_group_leader', 'member', 'best')
      and district_id is not null
      and small_group_id is not null
    )
  )
);

create table public.attendance_weeks (
  id bigint generated by default as identity primary key,
  week_start_date date not null unique,
  label text not null default '',
  created_at timestamptz not null default now()
);

create table public.attendance_records (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  attendance_week_id bigint not null references public.attendance_weeks(id) on delete cascade,
  event_type public.attendance_event_type not null,
  status public.attendance_status not null default 'unknown',
  note text not null default '',
  recorded_by_member_id bigint references public.members(id) on delete set null,
  recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attendance_records_one_row_per_event unique (member_id, attendance_week_id, event_type)
);

create table public.login_invites (
  id uuid primary key default gen_random_uuid(),
  member_id bigint not null references public.members(id) on delete cascade,
  invite_code text not null unique default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)),
  expires_at timestamptz not null,
  used_at timestamptz,
  used_by_line_user_id text,
  created_by_member_id bigint references public.members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint login_invites_code_not_blank check (length(btrim(invite_code)) >= 6)
);

create table public.line_auth_states (
  id uuid primary key default gen_random_uuid(),
  state text not null unique,
  code_verifier text not null,
  nonce text not null,
  redirect_to text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint line_auth_states_state_not_blank check (btrim(state) <> ''),
  constraint line_auth_states_code_verifier_not_blank check (btrim(code_verifier) <> ''),
  constraint line_auth_states_nonce_not_blank check (btrim(nonce) <> ''),
  constraint line_auth_states_redirect_to_not_blank check (btrim(redirect_to) <> '')
);

create table public.line_pending_logins (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  line_user_id text not null,
  display_name text not null default '',
  picture_url text not null default '',
  redirect_to text not null,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint line_pending_logins_token_hash_not_blank check (btrim(token_hash) <> ''),
  constraint line_pending_logins_line_user_id_not_blank check (btrim(line_user_id) <> ''),
  constraint line_pending_logins_redirect_to_not_blank check (btrim(redirect_to) <> '')
);

create table public.app_sessions (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  member_id bigint not null references public.members(id) on delete cascade,
  line_user_id text not null,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_sessions_token_hash_not_blank check (btrim(token_hash) <> ''),
  constraint app_sessions_line_user_id_not_blank check (btrim(line_user_id) <> '')
);

create index idx_big_families_district_id on public.big_families (district_id);
create index idx_small_groups_district_id on public.small_groups (district_id);
create index idx_small_groups_big_family_id on public.small_groups (big_family_id);
create index idx_members_line_user_id on public.members (line_user_id);
create index idx_members_district_role on public.members (district_id, role);
create index idx_members_big_family_role on public.members (big_family_id, role);
create index idx_members_small_group_role on public.members (small_group_id, role);
create index idx_attendance_records_week_event on public.attendance_records (attendance_week_id, event_type);
create index idx_attendance_records_member_week on public.attendance_records (member_id, attendance_week_id);
create index idx_login_invites_code on public.login_invites (invite_code);
create index idx_login_invites_member_id on public.login_invites (member_id);
create index idx_line_auth_states_state on public.line_auth_states (state);
create index idx_line_auth_states_expires_at on public.line_auth_states (expires_at);
create index idx_line_pending_logins_token_hash on public.line_pending_logins (token_hash);
create index idx_line_pending_logins_line_user_id on public.line_pending_logins (line_user_id);
create index idx_line_pending_logins_expires_at on public.line_pending_logins (expires_at);
create index idx_app_sessions_token_hash on public.app_sessions (token_hash);
create index idx_app_sessions_member_id on public.app_sessions (member_id);
create index idx_app_sessions_expires_at on public.app_sessions (expires_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists districts_set_updated_at on public.districts;
create trigger districts_set_updated_at
before update on public.districts
for each row
execute function public.set_updated_at();

drop trigger if exists big_families_set_updated_at on public.big_families;
create trigger big_families_set_updated_at
before update on public.big_families
for each row
execute function public.set_updated_at();

drop trigger if exists small_groups_set_updated_at on public.small_groups;
create trigger small_groups_set_updated_at
before update on public.small_groups
for each row
execute function public.set_updated_at();

drop trigger if exists members_set_updated_at on public.members;
create trigger members_set_updated_at
before update on public.members
for each row
execute function public.set_updated_at();

drop trigger if exists attendance_records_set_updated_at on public.attendance_records;
create trigger attendance_records_set_updated_at
before update on public.attendance_records
for each row
execute function public.set_updated_at();

drop trigger if exists login_invites_set_updated_at on public.login_invites;
create trigger login_invites_set_updated_at
before update on public.login_invites
for each row
execute function public.set_updated_at();

drop trigger if exists line_auth_states_set_updated_at on public.line_auth_states;
create trigger line_auth_states_set_updated_at
before update on public.line_auth_states
for each row
execute function public.set_updated_at();

drop trigger if exists line_pending_logins_set_updated_at on public.line_pending_logins;
create trigger line_pending_logins_set_updated_at
before update on public.line_pending_logins
for each row
execute function public.set_updated_at();

drop trigger if exists app_sessions_set_updated_at on public.app_sessions;
create trigger app_sessions_set_updated_at
before update on public.app_sessions
for each row
execute function public.set_updated_at();

create view public.member_directory as
select
  m.id,
  m.full_name,
  m.birthday,
  m.gender,
  m.note,
  m.role,
  m.is_admin,
  m.line_user_id,
  m.is_active,
  m.last_line_login_at,
  m.district_id,
  d.name as district_name,
  coalesce(m.big_family_id, sg.big_family_id) as big_family_id,
  bf.name as big_family_name,
  m.small_group_id,
  sg.name as small_group_name,
  m.created_at,
  m.updated_at
from public.members m
join public.districts d on d.id = m.district_id
left join public.small_groups sg on sg.id = m.small_group_id
left join public.big_families bf on bf.id = coalesce(m.big_family_id, sg.big_family_id)
;

alter table public.districts enable row level security;
alter table public.big_families enable row level security;
alter table public.small_groups enable row level security;
alter table public.members enable row level security;
alter table public.attendance_weeks enable row level security;
alter table public.attendance_records enable row level security;
alter table public.login_invites enable row level security;
alter table public.line_auth_states enable row level security;
alter table public.line_pending_logins enable row level security;
alter table public.app_sessions enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke all on public.member_directory from anon, authenticated;

grant usage on schema public to anon, authenticated;

comment on table public.members is 'All people in the church structure, including leaders, members, and bests.';
comment on table public.attendance_records is 'Weekly attendance records for each event type.';
comment on table public.login_invites is 'Invite codes used to bind a leader profile to a LINE identity.';
comment on table public.line_auth_states is 'Temporary LINE OAuth state and PKCE verifier storage.';
comment on table public.line_pending_logins is 'LINE identities waiting to be bound to an existing leader profile.';
comment on table public.app_sessions is 'App-owned session tokens issued after LINE identity verification.';

commit;

-- Setup notes
-- 1. Deploy the following Edge Functions with verify_jwt = false:
--    - line-login-start
--    - line-login-callback
--    - app-api
-- 2. Required function secrets:
--    - LINE_CHANNEL_ID
--    - LINE_CHANNEL_SECRET
--    - APP_FRONTEND_URL (optional for production; localhost/127.0.0.1 is allowed automatically)
-- 3. LINE Developers callback URL must be:
--    https://<your-project-ref>.supabase.co/functions/v1/line-login-callback
-- 4. Bootstrap the first leader manually, for example:
--
-- insert into public.districts (name, description)
-- values ('第一區', '系統初始區');
--
-- insert into public.members (
--   full_name,
--   role,
--   is_admin,
--   line_user_id,
--   district_id,
--   note
-- ) values (
--   '系統管理員',
--   'district_leader',
--   true,
--   '先用第一次 LINE 登入後看到的 line_user_id 替換這裡',
--   (select id from public.districts where name = '第一區'),
--   '系統初始管理員'
-- );
